# How to use:
#    cd hassio-google-drive-backup
#    gcloud config set project hassio-drive-backup
#    gcloud builds submit --config cloudbuild-dev.yaml --substitutions _DOCKERHUB_PASSWORD=<PASSWORD>

steps:
- name: "gcr.io/cloud-builders/docker"
  entrypoint: "bash"
  args: ["-c", "docker login --username=amarok77 --password=${_DOCKERHUB_PASSWORD}"]
- name: 'gcr.io//docker'
  args: [ 'build', '-f', 'Dockerfile-addon',  '-t', 'amarok77/bticino-x8000-amd64:${_VERSION}', "--build-arg", "BUILD_FROM=homeassistant/amd64-base", '.' ]
substitutions:
  _DOCKERHUB_PASSWORD: "define me" # default value
  _VERSION: "dev-testing" # default value
images:
- "amarok77bticino-x8000-amd64:${_VERSION}"
